[package]
name = "wal"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "size"
path = "src/size.rs"
test = false

[[bin]]
name = "wal"
path = "src/main.rs"
test = false

[[bench]]
name = "bc"
harness = false

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
